- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: "Config xdebug"
  copy: src=/vagrant/ansible/roles/phpcommon/files/xdebug.ini dest=/etc/php5/mods-available/xdebug.ini
  notify: restart apache
