---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant
    sys_packages: ["vim"]
    php_packages: ["php5-cli","php5-common","php5-mcrypt","php5-memcache","php5-memcached","php5-intl"]
    php_ppa: php5
    mysql_user: db_user
    mysql_user_pass: vA7YyMWdRx
    mysql_root_password: mpass
    mysql_databases: ["yii2test"]
  tasks:
  - name: adapt my.cnf
    ini_file: dest=/etc/mysql/my.cnf section=mysqld option=max_connections value=400 backup=yes
